services:
  - type: web
    name: standupsync
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn standupsync.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com 