# Generated by Django 5.0.2 on 2025-06-03 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="invite_code",
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
