# Generated by Django 3.2.25 on 2025-06-01 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250602_0243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standupentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'Stand-up entries'},
        ),
        migrations.AddField(
            model_name='standupentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standupentry',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='standupentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
