# Generated by Django 3.2.25 on 2025-06-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250602_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='standupentry',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
