# Generated by Django 5.1.2 on 2025-06-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_standupentry_ai_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standupentry",
            name="ai_summary",
        ),
    ]
