# Generated by Django 5.0.2 on 2025-06-03 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_team_description_team_members_alter_team_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="standupentry",
            name="blockers_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="standupentry",
            name="today_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="standupentry",
            name="yesterday_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="standupentry",
            name="blockers",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="standupentry",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="standupentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("blocked", "Blocked"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
